 CREATE TABLE PROPRIETARIO(
 ID BIGINT NOT NULL auto_increment,
 NOME VARCHAR(50) NOT NULL,
 EMAIL VARCHAR(100) NOT NULL,
 TELEFONE VARCHAR(20) NOT NULL,
 PRIMARY KEY (ID)
 );

 ALTER TABLE PROPRIETARIO ADD CONSTRAINT UK_PROPRIETARIO UNIQUE (EMAIL);